### ISSUE TITLE
NumberFormatException with too long patch numbers

### ISSUE THREAD

**Issue by jmfernandez** [pilosus/action-pip-license-checker#43]
I have this action integrated in one of my Python projects, so each time a push is done, it checks the licences of the needed Python packages. The list is obtained through `pip freeze`.

The point is that the issue described at https://github.com/pilosus/pip-license-checker/issues/136 has started happening due a too long patch number in an indirect dependency (in this case `schema-salad-8.4.20230213094415`).

Once the issue is fixed at https://github.com/pilosus/pip-license-checker in a newer release, could you also release an update of the action using that newer release, please? Current one is using 0.44.0

https://github.com/pilosus/action-pip-license-checker/blob/941b76dd138ba125db40753243e1751a8c01ca55/Dockerfile#L1

Thanks in advance!

**Comment by pilosus** [comment]
Hi @jmfernandez thanks for reporting.
Can you please check if your problem is solved with this?

```
uses: pilosus/action-pip-license-checker@8dab363961dde61d6036887e4dc2ee43f5bfd598
```

If yes, feel free to use it if the matter is urgent.
Because I'll need more time to prep the proper release for the action, as the upstream checker had some potentially breaking changes when migrating from version 0.44 to 0.45.0. It's unlikely that I'll be able to release it until the next week or two.
But using the action with the commit rather than tag should help to solve your problem.

**Comment by jmfernandez** [comment]
I have been able to narrow it down to the specific case of `pycparser==2.21`, as I have just described at https://github.com/pilosus/pip-license-checker/issues/138

**Comment by pilosus** [comment]
@jmfernandez should be fixed with:
```
uses: pilosus/action-pip-license-checker@d574bc40bf5b18db8920ad4fff1ee376abb6db28
```
let me know if it solves both bugs

**Comment by jmfernandez** [comment]
I can confirm you it fixes the issue with the action.

Thanks!
